version: "3"

services:
  votewasm:
    build: Vote/
    container_name: votewasm
    restart: always
    ports:
      - 80:80

  voteapi:
    build: VoteServer/
    image: voteserver
    container_name: voteserver
    restart: always
    ports:
      - "5001"
#Не забудь про db
  
      

      
      