// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoteServer;

namespace VoteServer.Migrations
{
    [DbContext(typeof(VoteDBContext))]
    partial class VoteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VoteServer.VoteInfo", b =>
                {
                    b.Property<string>("TitleVoting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescriptionVoting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_dateVoting")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_dateVoting")
                        .HasColumnType("datetime2");

                    b.HasKey("TitleVoting");

                    b.ToTable("VoteInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
